const $=id=>document.getElementById(id);let DB=JSON.parse(localStorage.getItem("v6db")||"null")||window.DEMO;let F=JSON.parse(localStorage.getItem("v6fav")||"[]");
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");scrollTo(0,0)}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function strip(s){return String(s||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}
function save(){localStorage.setItem("v6db",JSON.stringify(DB))}
function fav(id){F=F.includes(id)?F.filter(x=>x!==id):F.concat(id);localStorage.setItem("v6fav",JSON.stringify(F));render()}
function card(x){return `<article class="tile"><div class="cover">${x.icon||"📜"}</div><h3>${esc(x.title)}</h3><p>${esc(x.description||strip(x.content).slice(0,180))}</p><small>${esc(x.place||"")} ${x.year?"• "+x.year:""}</small><button onclick="detail('${x.id}')">Ouvrir</button><button onclick="fav('${x.id}')">${F.includes(x.id)?"★ Favori":"☆ Favori"}</button></article>`}
function detail(id){let x=DB.find(a=>a.id===id);$("detail").innerHTML=`<h2>${esc(x.title)}</h2><p>${esc(x.place||"")} • ${x.year||""}</p>${x.content?`<div>${x.content}</div>`:`<p>${esc(x.description||"")}</p>`}<div class="gallery">${(x.imageUrls||[]).map(u=>`<img src="${esc(u)}">`).join("")}</div><p>${(x.labels||[]).map(t=>`<small>${esc(t)} </small>`).join("")}</p>${x.url?`<button onclick="location.href='${esc(x.url)}'">Article original</button>`:""}`;$("modal").classList.add("open")}
function closeModal(){$("modal").classList.remove("open")}
function search(){let q=($("q")?.value||"").toLowerCase();$("results").innerHTML=DB.filter(x=>[x.title,x.place,x.period,x.collection,x.description,x.content,...(x.labels||[])].join(" ").toLowerCase().includes(q)).map(card).join("")||"<div class='panel'>Aucun résultat.</div>"}
function gene(){let q=$("gq").value.toLowerCase();$("geneGrid").innerHTML=DB.filter(x=>[x.title,x.place,x.description,x.content,...(x.labels||[])].join(" ").toLowerCase().includes(q)).map(card).join("")}
function render(){let cols=[...new Set(DB.map(x=>x.collection||"Archives"))];$("n").textContent=DB.length;$("ni").textContent=DB.reduce((n,x)=>n+(x.imageUrls?.length||0),0);$("nc").textContent=cols.length;$("nf").textContent=F.length;$("homeCards").innerHTML=DB.slice(0,8).map(card).join("");$("collectionsGrid").innerHTML=cols.map(c=>`<article class="tile"><div class="cover">📚</div><h3>${esc(c)}</h3><p>${DB.filter(x=>x.collection===c).length} documents</p></article>`).join("");$("places").innerHTML=DB.filter(x=>x.place).map(card).join("");$("pins").innerHTML=DB.filter(x=>x.x&&x.y).map(x=>`<button class="pin" style="left:${x.x}%;top:${x.y}%" onclick="detail('${x.id}')">📍</button>`).join("");$("timelineGrid").className="timeline";$("timelineGrid").innerHTML=[...DB].filter(x=>x.year).sort((a,b)=>a.year-b.year).map(x=>`<article class="event"><b>${x.year}</b><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></article>`).join("");search();gene();$("favGrid").innerHTML=DB.filter(x=>F.includes(x.id)).map(card).join("")||"<div class='panel'>Aucun favori.</div>"}
$("q").addEventListener("input",search);$("gq").addEventListener("input",gene);
$("file").addEventListener("change",async e=>{try{let d=JSON.parse(await e.target.files[0].text());DB=[...(d.posts||[]),...(d.pages||[])].map((x,i)=>({id:String(x.id||i),title:x.title||"Sans titre",collection:x.labels?.[0]||"Archives Blogger",year:x.published?new Date(x.published).getFullYear():null,place:x.location?.name||"",description:strip(x.content).slice(0,220),content:x.content||"",labels:x.labels||[],url:x.url||"",imageUrls:x.extractedImageUrls||[]}));save();render();$("status").textContent=`Import réussi : ${DB.length} documents.`}catch(e){$("status").textContent="Erreur : "+e.message}});
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});render();